name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Lint code
      run: |
        pip install ruff
        ruff check .

    - name: Run tests
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml
    
    - name: Run tests with coverage
      run: |
        pytest --cov=sigtool --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4



    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-py${{ matrix.python-version }}
        path: junit/test-results.xml

